name: publish

on:
  push:
    branches:
      - main
      - devel

jobs:
  publish-rhomis-api-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the api image
        run: |
          docker build . --tag ghcr.io/l-gorman/rhomis-data-r-scripts:latest
          docker image push ghcr.io/l-gorman/rhomis-data-r-scripts:latest
          docker push ghcr.io/l-gorman/rhomis-data-r-scripts:latest
